### ISSUE TITLE
DOMParser not defined

### ISSUE THREAD

**Issue by aleixo** [timbenniks/gpx-for-runners#3]
I am trying to user the lib on my backend as follows.

`let gpxR       = require('gpx-for-runners');`
`const gpxContent = fs.readFileSync(__dirRoot + '/public/files/gpx/sample.gpx');`
`const gpx = new gpxR(gpxContent);`

When i run it get he following error:

ReferenceError: DOMParser is not defined
    at new t (/home/diogo-gocontact/Documents/server/node_modules/gpx-for-runners/lib/gpx.min.js:1:1014)
    at /home/diogo-gocontact/Documents/server/controllers/user/user.js:50:23
    at /home/diogo-gocontact/Documents/server/node_modules/gpx-parse/lib/gpx-parse.js:179:14
    at Parser.<anonymous> (/home/diogo-gocontact/Documents/server/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:159:13)
    at SAXParser.onclosetag (/home/diogo-gocontact/Documents/server/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/diogo-gocontact/Documents/server/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/diogo-gocontact/Documents/server/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/diogo-gocontact/Documents/server/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/diogo-gocontact/Documents/server/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/diogo-gocontact/Documents/server/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/diogo-gocontact/Documents/server/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/home/diogo-gocontact/Documents/server/node_modules/xml2js/lib/parser.js:354:19)
    at Object.exports.parseGpx (/home/diogo-gocontact/Documents/server/node_modules/gpx-parse/lib/gpx-parse.js:154:2)
    at /home/diogo-gocontact/Documents/server/node_modules/gpx-parse/lib/gpx-parse.js:200:11
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

Can you help me please.

**Comment by timbenniks** [comment]
Hi, this is happening due to the fact that the DOMParser is a browser component which does not exist within the nodejs context. 

You could do a pull request where you use a nodejs equivalent module like xmldom if you are in the nodejs context. I will also have a look into this.

**Comment by timbenniks** [comment]
#resolved the issue, updated to version 1.0.5 on npm. see: https://www.npmjs.com/package/gpx-for-runners

**Comment by fabulator** [comment]
@timbenniks Hi, I tried to use this library and I faced several node related issues:
1. Library does not detect that is executed by Node. There have to be some problem with webpack compiling because it rewrite global process variable.

2. New instance of DOMParser have to be created. DOMParser.parseFromString does not work. new DOMParser().parseFromString is ok

3. Methods querySelectorAll and querySelector are not defined in xmldom library. You have to use eg. this.xmlDoc.documentElement.getElementsByTagName( 'trkpt' )

**Comment by timbenniks** [comment]
@fabulator thanks for your comments. I'll have a look at this asap. I never meant for the module to work in node, than someone requested it and I did a poor job in adding the functionality.

**Comment by fabulator** [comment]
Totally understand. No need to hurry. I needed to use this library only one time so I just made fast fixes for myself and give you steps how to fix it in library.

**Comment by timbenniks** [comment]
@fabulator @ElGoorf see 1.0.6 release on npm. Should be much better :)

**Comment by fabulator** [comment]
@timbenniks I tried you last update and it works great with node. Thank you very much.
