### ISSUE TITLE
Ionic 3 undefined .textContext

### ISSUE THREAD

**Issue by forestgun** [timbenniks/gpx-for-runners#4]
I am trying to user the lib on my ionic 3 app as follows.

   import GpxForRunners from 'gpx-for-runners';
   ... 
    this._http.get('minitraildocastelo18itra.gpx', { responseType: 'text' }).subscribe( response => {  
      const gpx = new GpxForRunners (response);
      this.distance = gpx.distance();

    });

TypeError: Cannot read property 'textContent' of null
    at GPX.createJsonFromGpxDom (http://localhost:8100/build/vendor.js:186824:48)
    at new GPX (http://localhost:8100/build/vendor.js:186790:30)
    at SafeSubscriber._next (http://localhost:8100/build/main.js:771:23)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:37700:16)
    at SafeSubscriber.next (http://localhost:8100/build/vendor.js:37647:22)
    at Subscriber._next (http://localhost:8100/build/vendor.js:37587:26)
    at Subscriber.next (http://localhost:8100/build/vendor.js:37551:18)
    at MapSubscriber._next (http://localhost:8100/build/vendor.js:56285:26)
    at MapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:37551:18)
    at FilterSubscriber._next (http://localhost:8100/build/vendor.js:150425:30)

**Comment by timbenniks** [comment]
@forestgun new release on npm: 1.0.6
